FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/order-service-publisher /app/cmd/publisher/main.go

FROM alpine AS publisher_app
WORKDIR /app
COPY --from=builder /app/order-service-publisher /app/order-service-publisher
CMD ["/app/order-service-publisher"]