FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/order-service-consumer /app/cmd/consumer/main.go

FROM alpine AS consumer_app
WORKDIR /app
COPY --from=builder /app/order-service-consumer /app/order-service-consumer
CMD ["/app/order-service-consumer"]